baseURL = 'https://exploration-lab.github.io/'
languageCode = 'en-us'
title = 'Exploration Lab'
theme = 'hugo-universal-theme'
themesDir = "./themes"

[params]
    disabled_logo = false
    logo_text = "Exploration Lab Logo"
    logo = "img/logo3.png"
    logo_small = "img/logo3-onlyletters.png"

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    mainSections = ["news", "research", "explorers"]

# Enable or disable top bar with social icons
[params.topbar]
    enable = false

[menu]

[[menu.main]]
    name = "About"
    identifier = "menu.about"
    url = "/about"
    weight = 1
    # pre = "<i class='fas fa-circle-info fa-2xl' style='height: 1ch'></i>"
    # pre = '<span class="material-symbols-outlined" style="font-size: 8ch">info</span>'
    pre = "<img src='img/about.png' width='70px' />"

[[menu.main]]
    name = "Research"
    identifier = "menu.research"
    url = "/research"
    weight = 2
    pre = "<img src='img/testtube.png' width='70px' />"

[[menu.main]]
    name = "News"
    identifier = "menu.news"
    url = "/news"
    weight = 3
    pre = "<img src='img/news.png' width='70px' />"

[[menu.main]]
    name = "Explorers"
    identifier = "menu.team"
    url = "/explorers"
    weight = 4
    pre = "<img src='img/team.png' width='70px' />"

[[menu.main]]
    name = "Openings"
    identifier = "menu.openings"
    url = "/openings"
    weight = 5
    pre = "<img src='img/openings.png' width='70px' />"

[[menu.main]]
    name = "Contact"
    identifier = "menu.contact"
    url = "/contact"
    weight = 6
    pre = "<img src='img/contact.png' width='70px' />"


[[menu.topbar]]
    weight = 1
    name = "Phone"
    url = "tel:+12 34 567 89 01"
    pre = "<i class='fas fa-2x fa-phone'></i>"
